### PR TITLE
Added templates using Jinja2 for easily creating web pages.

### PR DESCRIPTION
**Pull request by KyleStank**
^^^^^

### CODE REVIEW

**Comment by KyleStank** [comment]
Idk how there is a problem with about.html and index.html. If you really need to, merge, clone my project, and then copy and paste the contents of my about.html and index.html, and paste them into your about.html and index.html.

**Comment by mypetbirdrules** [comment]
I hope I'm not destroying anything.

**Comment by KyleStank** [comment]
Your not destorying anything. They are minor conflicts. I can fix them myself tommorrow and submit a new Pull Request if you want.

**Comment by KyleStank** [comment]
Just added a lot. Changed look of site, organized the structure of the site, according to this:
http://flask.pocoo.org/docs/0.11/patterns/packages/

**Pull request merged**
